### PR TITLE
introduced ungetHandler for ModuleHandlerFactory

### PR DESCRIPTION
**Pull request by BenediktNiehues**
Signed-off-by: Benedikt Niehues b.niehues@external.telekom.de

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Can you update this PR to cover the latest discussion on Skype?

**Comment by BenediktNiehues** [comment]
@kaikreuzer I created an extra issue for the ruleId to be contained in the get/ungetHandler method, as mentioned in Skype. (Issue #104) If you mean that.

**Comment by kaikreuzer** [comment]
So the answer is no then? I thought it makes sense to have just one PR, because this one now only implements half of what has been discussed.

**Comment by BenediktNiehues** [comment]
This solves issues #104, #85 and hopefully #102

**Pull request merged**
