### PR TITLE
introducing generic compare condition

### PR DESCRIPTION
**Pull request by BenediktNiehues**
Signed-off-by: Benedikt Niehues b.niehues@external.telekom.de

### CODE REVIEW

**Comment by marinmitev** [comment]
The groovy test in this PR is testing directly the java code of CompareConditionHandler. 
There should be added new test rule in json file with condition of type GenericCompareCondition and with item trigger and item action.
Regarding the logic of this GenericCompareCondition - it defines both input object and a config property "inputProperty" - assuming that this is a key of the input object map. I am not sure how generic is this usecase, wouldn't it be more general to have a simple object on the input like number or string and not a map?

**Comment by BenediktNiehues** [comment]
Yes, you are right, I can create an integration tests for this module. The InputProperty is used for example if you have an Event as input, but only want to compare the property payload, then you can add inputProperty=payload to your configuration.

**Comment by marinmitev** [comment]
what about if the trigger output is not an event but a simple string or boolean, will this condition fit - then probably in rule there will be only an input object, but no configuration for inputProperty

**Comment by BenediktNiehues** [comment]
If the input is a string or a primitive type, the inputProperty has not to be set. But in deed you are right, if the input is a String and the inputProperty is set, then the value which will be compared is null. 
I can simply set the compareValue to the input if the get-method runs into trouble. (catch in getCompareValue). But better is to don't do the reflection part when input is instance of any primitive type or String.

**Pull request merged**
