### PR TITLE
Rename TriggerImpl, ConditionImpl, CommandImpl and RuleImpl to

### PR DESCRIPTION
**Pull request by danchom**
RuntimeTrigger, RuntimeAction, RuntimeCondition and RuntimeRule

Signed-off-by: Yordan Mihaylov j.mihailov@prosyst.bg

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Which issue/discussion does this PR relate to? I am just wondering about the naming...

**Comment by danchom** [comment]
This proposal came from Denis. He said that the Impl suffix of condition, actions and etc. does not have any meaning after removing their interfaces. We are agree for this change.

**Comment by dnobel** [comment]
The problem was that now the Rule, Action etc classes are not longer interfaces, so they are already implementation. It does not makes sense to call them RuleImpl. We discussed possible names and came up with "Runtime" prefix, another option was "Active".

Don´t you like the name @kaikreuzer ?

**Comment by kaikreuzer** [comment]
Are these classes part of the API or just internal classes? If the latter, the name is ok for me.

**Comment by BenediktNiehues** [comment]
For me the Renaming makes the purposes of the classes more clear, I like it this way.
@kaikreuzer yes, they are all internal.
I reviewed the PR and have no comments on it.

**Comment by kaikreuzer** [comment]
Great, thanks for the clarification! 
Am 01.09.2015 2:51 nachm. schrieb BenediktNiehues notifications@github.com:For me the Renaming makes the purposes of the classes more clear, I like it this way.
@kaikreuzer yes, they are all internal.
I reviewed the PR and have no comments on it.

**Pull request merged**
